# Generated by Django 3.2.11 on 2022-02-16 09:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('icono', models.URLField(blank=True, max_length=255)),
                ('seleccion', models.CharField(blank=True, max_length=255)),
                ('partidos', models.PositiveIntegerField(blank=True)),
                ('goles', models.PositiveIntegerField(blank=True)),
                ('penaltis', models.PositiveIntegerField(blank=True)),
                ('media', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'goleadores',
            },
        ),
        migrations.CreateModel(
            name='GoleadoresIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
