# Generated by Django 3.2.11 on 2022-02-21 11:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('info', wagtail.core.fields.RichTextField(blank=True)),
                ('date', models.DateField(verbose_name='Fecha Post')),
            ],
            options={
                'verbose_name_plural': 'Noticias breves',
            },
        ),
    ]
