# Generated by Django 3.2.11 on 2022-02-21 15:16

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cuerpo', wagtail.core.fields.RichTextField(blank=True)),
                ('date', models.DateField(verbose_name='Fecha Publicación')),
            ],
        ),
    ]
