# Generated by Django 3.2.11 on 2022-02-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactopage_noticiablog'),
        ('blog', '0004_alter_noticia_titulo'),
    ]

    operations = [
    ]
