# Generated by Django 3.2.11 on 2022-02-23 22:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0005_auto_20220208_1042'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0007_viajepagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajepagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.viajepage'),
        ),
        migrations.CreateModel(
            name='PeliCommentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('comentario', wagtail.core.fields.RichTextField(blank=True)),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pelis.pelicula')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
