# Generated by Django 3.2.11 on 2022-02-23 22:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0005_auto_20220208_1042'),
        ('blog', '0008_auto_20220223_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicommentpage',
            name='pelicula',
        ),
        migrations.CreateModel(
            name='PeliCommentPeliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='blog.pelicommentpage')),
                ('pelicula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pelis.pelicula')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
