# Generated by Django 3.2.11 on 2022-03-01 08:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_pelicommentgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
