# Generated by Django 3.2.11 on 2022-01-20 11:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=4, default='0', max_digits=6)),
                ('link', models.URLField(default='')),
                ('place', models.PositiveIntegerField(default='0')),
                ('year', models.PositiveIntegerField(default='0')),
                ('imagen', models.URLField(default='')),
                ('title', models.CharField(default='', max_length=255, verbose_name='título')),
                ('reparto', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='PelisIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
