# Generated by Django 3.2.11 on 2022-01-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='place',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='rating',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='reparto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='title',
            field=models.CharField(max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
