# Generated by Django 3.2.11 on 2022-01-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0002_auto_20220120_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='resumen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='place',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='reparto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
